CREATE TABLE `schedules` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`company_id` integer NOT NULL,
	`user_id` integer NOT NULL,
	`sale_id` integer,
	`title` text NOT NULL,
	`description` text,
	`customer_name` text,
	`customer_phone` text,
	`location` text,
	`status` text DEFAULT 'pending' NOT NULL,
	`type` text DEFAULT 'other' NOT NULL,
	`date` integer NOT NULL,
	`start_time` text,
	`end_time` text,
	`whatsapp_sent` integer DEFAULT false NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`sale_id`) REFERENCES `sales`(`id`) ON UPDATE no action ON DELETE set null
);
